name: fstories_widget
description: Flutter package that allows you to use stories mechanism in your Flutter app. It can customizeble. Package don't use external dependencies.
version: 0.0.6
homepage: https://github.com/pawees/fstories_widget

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  shared_preferences: ^2.3.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # no Flutter configuration